---
defaults: &defaults
  github:
    site: <%= ENV['GITHUB_SITE'] %>
    client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
    client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
  ci:
    system: jenkins
    site: https://localhost:8080/

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
